# Generated by Django 5.0.6 on 2024-06-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/profile.jpg', null=True, upload_to='images'),
        ),
    ]
